steps:
- name: 'gcr.io/cloud-builders/docker'
  script: |
    docker build -t us-west2-docker.pkg.dev/$PROJECT_ID/personalfinancial-sboot-jdk8-repo/personalfinancial-sboot-jdk8:tag1 .
  automapSubstitutions: true
images:
- 'us-west2-docker.pkg.dev/$PROJECT_ID/personalfinancial-sboot-jdk8-repo/personalfinancial-sboot-jdk8:tag1'