apiVersion: v1
kind: Namespace
metadata:
  name: personal
  labels:
    app: personal
---
apiVersion: v1
kind: Service
metadata:
  name: personalfinancial-sboot-jdk8-1
  namespace: personal
  annotations:
    harness.io/primary-service: "true"
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: personalfinancial-sboot-jdk8-2
  namespace: personal
  annotations:
    harness.io/stage-service: "true"
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: personalfinancial-sboot-jdk8
  namespace: personal
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: renanl/personalfinancial-sboot-jdk8:{{ .Values.image.tag }}
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 8080
