apiVersion: v1
kind: Service
metadata:
  name: personalfinancial-sboot-jdk8
  namespace: personal
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer