name: Java CI with Maven
on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
jobs:
  build:
    runs-on: ubuntu-latest
    container: openjdk:11
    steps:
    - uses: actions/checkout@v3
    - name: Set up
      run: apt update && apt install maven -y
    - name: Build with Maven
      run: mvn compile
  unit-tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Unit tests
        run: mvn test
      - name: Install Package
        run: mvn install -DskipTests
  generate-docker-image:
    needs: unit-tests
    runs-on: ubuntu-latest
    steps:
    - name: Setup Build Image
      uses: docker/setup-buildx-action@v2.0.0
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        username: renanl
        password: ${{ secrets.PASSWORD_DOCKER_HUB }}
