name: Java CI with Maven
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container: openjdk:11
    steps:
    - uses: actions/checkout@v3
    - name: Set up
      run: apt update && apt install maven -y
    - name: Build with Maven
      run: mvn compile
    - name: Unit tests
      run: mvn test
